import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./providers/StoreProvider";


export const metadata: Metadata = {
  title: "Solaris Client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
    </StoreProvider>
  );
}
